### ISSUE TITLE
DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by amyyenjungpeng** [ktlast/punch_in_icehrm#1]
### 錯誤訊息

```
[amy@a129 auto-punch]$ /usr/local/bin/python3 /home/amy/auto-punch/punch.py -f /home/amy/auto-punch/config.yaml
[DEBUG]: Initializing ...
Traceback (most recent call last):
  File "/home/amy/auto-punch/punch.py", line 251, in <module>
    pw = PunchWorker(email_address=next(iter(config['users'])))
  File "/home/amy/auto-punch/punch.py", line 155, in __init__
    self.driver = webdriver.Chrome(service=s, options=chrome_options)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 72, in __init__
    service_log_path, service, keep_alive)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 97, in __init__
    options=options)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 276, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 369, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 434, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
```

### 嘗試 debug 作法
- https://www.codeleading.com/article/63045589278/
 
1. 檢查版本

```
[amy@a129 chrome]$ pwd
/opt/google/chrome
[amy@a129 chrome]$ ./google-chrome --version
Google Chrome 104.0.5112.79
```

```
[amy@a129 opt]$ ./chromedriver --version
ChromeDriver 104.0.5112.79 (3cf3e8c8a07d104b9e1260c910efb8f383285dc5-refs/branch-heads/5112@{#1307})
```

2. `punch.py` 加上 options 參數

```
 chrome_options.add_argument('--no-sandbox')
 chrome_options.add_argument('--disable-dev-shm-usage')
```

以上檢查、調整完，還是有同樣的錯誤。😮‍💨

**Comment by ktlast** [comment]
先嘗試把 chrome 關掉重啟

查找：
```
ps -ef |grep chrome
```

---

看了這篇：
- https://stackoverflow.com/questions/56637973/how-to-fix-selenium-devtoolsactiveport-file-doesnt-exist-exception-in-python

目前不太確定具體的原因，我這兩天再找環境測試，會再推一版

**Comment by amyyenjungpeng** [comment]
目前猜測可能原因為版本太新 😓

**Comment by ktlast** [comment]
咦 rollback 到舊版就會動嗎

**Comment by amyyenjungpeng** [comment]
我用舊版 `99.0.4844.51` 之後，init 沒有再跳錯，可是又有新的問題了 QQQ

**Comment by amyyenjungpeng** [comment]
新的問題是 timeout，後來把  `self.driver.set_page_load_timeout(10) # wait page load up to 10 seconds.` 的時間調久一點就可以了！！！

**Comment by ktlast** [comment]
docker 起 centos 7 
chrome 版本 `99.0.4844.51` 有一樣的錯誤

**Comment by ktlast** [comment]
參考這篇
- https://stackoverflow.com/questions/56637973/how-to-fix-selenium-devtoolsactiveport-file-doesnt-exist-exception-in-python

加上了 `chromeOptions.add_argument("--remote-debugging-port=9222")` 應該就可以了


目前我用 docker 起 CentOS 後續有卡 chrome 起不來；排除中
